### ISSUE TITLE
Why start your snippets with `<md`?

### ISSUE THREAD

**Issue by stephnr** [devotis/sublime-angular-material-snippets#5]
I often use emmet when writing my code. I would highly recommend just making `md-` the trigger point instead

**Comment by christiaanwesterbeek** [comment]
Seems like a good suggestion and one that fixes an issue that [I mentioned](https://github.com/devotis/sublime-angular-material-snippets#todo) on README.md. In the directives I have defined the tabTrigger like this: `<tabTrigger>md-autocomplete</tabTrigger>` and that seems fine. I don't know where to implement the fix you mentioned.

**Comment by stephnr** [comment]
No change needed from that end. Instead of activating it with `<md` you just use `md-` and then use <kbd>Ctrl</kbd>+<kbd>Space</kbd>
